fragment vehicleUpdateFragment on VehicleUpdate {
    bearing
    delay
    destinationName
    expirationEpochSecond
    inCongestion
    lastUpdatedEpochSecond
    line {
        lineRef
        lineName
        publicCode
    }
    location {
        latitude
        longitude
    }
    mode
    monitored
    monitoredCall {
        order
        stopPointRef
        vehicleAtStop
    }
    occupancyStatus
    originName
    progressBetweenStops {
        percentage
        linkDistance
    }
    serviceJourney {
        id
    }
    speed
    vehicleId
    vehicleStatus
}
